# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vintage <- function(z1, z2, Q, lambdas1, lambdas2, n, p, k, init_D, maxIterEM, tolEM, scenario, B, save_profile = 1L) {
    .Call(`_VINTAGE_vintage`, z1, z2, Q, lambdas1, lambdas2, n, p, k, init_D, maxIterEM, tolEM, scenario, B, save_profile)
}

